### ISSUE TITLE
how to get 'psp_ffhq_toonify.pt'

### ISSUE THREAD

**Issue by huangfaan** [justinpinkney/toonify#10]
Hello, thanks for your job. I am interested in the toonification, and I tried to do it according to your ideas, but now I have some difficulties. So I want to know about the 'psp_ffhq_toonify.pt' clearly. Can you tell me the detailed process of getting it? The more detailed the better, thaknk you, I am look forward to receiving your response.

**Comment by wennycooper** [comment]
Hi, I'm also interested to know how to trained 'psp_ffhq_toonify.pt'.
what's the lambda (l1, l2, l3, l4) combinations? we just put the real image in the input of the psp encoder and the toonified images as the ground truth?  And hints will be very appreciated.

**Comment by justinpinkney** [comment]
I think you're looking for this: https://github.com/eladrich/pixel2style2pixel#pretrained-models

https://drive.google.com/file/d/1YKoiVuFaqdvzDP5CZaqa3k5phL-VDmyz/view
