### ISSUE TITLE
Getting error "UnpicklingError: invalid load key, '<'." on Google Colab

### ISSUE THREAD

**Issue by NoJustAnother** [justinpinkney/toonify#14]
When running this cell (https://colab.research.google.com/github/justinpinkney/toonify/blob/master/toonify-yourself.ipynb#scrollTo=cwVXBFaSuoIU) on Google Colab, I get the following error:
```
Downloading https://drive.google.com/uc?id=1H73TfV5gQ9ot7slSed_l-lim9X7pMRiU ... done
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
[<ipython-input-12-352be5b547c8>](https://localhost:8080/#) in <module>()
      6 ffhq_url = "http://d36zk2xti64re0.cloudfront.net/stylegan2/networks/stylegan2-ffhq-config-f.pkl"
      7 
----> 8 _, _, Gs_blended = pretrained_networks.load_networks(blended_url)
      9 _, _, Gs = pretrained_networks.load_networks(ffhq_url)

[/content/stylegan2/pretrained_networks.py](https://localhost:8080/#) in load_networks(path_or_gdrive_path)
     74     tflib.init_tf()
     75     with stream:
---> 76         G, D, Gs = pickle.load(stream, encoding='latin1')
     77     _cached_networks[path_or_url] = G, D, Gs
     78     return G, D, Gs

UnpicklingError: invalid load key, '<'.
```
I am unable to find any solution for this. How to solve this problem?

**Comment by justinpinkney** [comment]
This usually means the file has been downloaded too many times and access is being restricted. If you try and download it with the gdown command you might see the following.
![image](https://user-images.githubusercontent.com/605492/155969001-db73848e-bd4e-434b-977f-744397e0004b.png)

Probably you will still be able to download it if you open the link in the web browser (even more likely if you are logged into a google account). After manually downloading, upload the file to colab and change line 5 to point to the file you just uploaded:

`blended_url = "/content/path/to/file/you/uploaded" `

**Comment by mahnoor-fatima-saad** [comment]
Hi @justinpinkney 
 
I tried manually downloading and uploading both the blended_url and the ffhq_url but this didn't resolve the issue. 

Could you please guide me?
 
![image](https://user-images.githubusercontent.com/45865489/163565445-01c87c13-b1f2-4c8d-a514-e82313471331.png)
