### ISSUE TITLE
ModuleNotFoundError: No module named 'pretrained_networks'

### ISSUE THREAD

**Issue by kumari-jaya** [justinpinkney/toonify#18]

**Comment by justinpinkney** [comment]
please provide more context

**Comment by kumari-jaya** [comment]
@justinpinkney The repository stylegan2 doesn't support python3 or tensorflow2.0 

Probably the reason for error.

**Comment by justinpinkney** [comment]
it supports python3 but not tf2, so probably the issue.

**Comment by kumari-jaya** [comment]
Are we seeing tf2 compatibility in near future ?

**Comment by justinpinkney** [comment]
> Are we seeing tf2 compatibility in near future ?

Afraid not, but there is a pytorch version instead: https://github.com/justinpinkney/toonify/issues/19#issuecomment-1222457573

**Comment by kumari-jaya** [comment]
No problem . Thanks a lot.

**Comment by ghost** [comment]
I have also encountered the same issue. I am using python version 3.7 and tensorflow==1.15.0. Did you find any solution to this problem ?
