### ISSUE TITLE
Running the project on TF 2.X

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [justinpinkney/toonify#19]
Dear Sir,

I am trying to configure the project in the TF 2.x and facing a number of problems (features of TF 1.x that are not there in the TF 2.x). Can you just tell me, whether this project migration from TF 1.x to TF 2.x will be possible OR not?

Thank You

**Comment by justinpinkney** [comment]
Unfortunately I'm not planning on doing any work for TF2. There is support for StyleGAN and layer swapping in PyTorch instead: https://github.com/dvschultz/stylegan2-ada/blob/main/blend_models.py
