### ISSUE TITLE
tensorflow_version 1.x / cuda 11 / latest graphics drivers for 3090

### ISSUE THREAD

**Issue by johndpope** [justinpinkney/toonify#4]
Hi Justin,
I bought a new graphics card - 3090 24gb / was planning to use it to render out toon images.
but... I noticed today - using  this great distro / ubuntu with nvidia drivers https://pop.system76.com/
that nvidia is targeting cuda 11 for the driver 455 from nvidia.

Not sure which way to go on this 
1. upgrade code to tensorflow 2 
2. or downgrade os to older driver.
3. Run the code is a docker container .... 

once upon a time - I'd upgrade python2 code to python 3 - just by runnig 2to3 command
I saw this https://www.tensorflow.org/guide/upgrade

Is there any thoughts on this? was this ever attempted - too hard basket?
any thoughts appreciated - thanks in advance

colab is straightforward but not suitable for my needs.

**Comment by justinpinkney** [comment]
I have no idea how it would be to convert to tf2. I'd be too scared to try! Personally I always go with docker for running tf stuff locally as it's such a massive pain with versions etc. https://hub.docker.com/r/tensorflow/tensorflow/

There's a dockerfile in my stylegan2 repo here: https://github.com/justinpinkney/stylegan2/blob/master/Dockerfile

**Comment by johndpope** [comment]
Thanks Justin

**Comment by johndpope** [comment]
fyi - https://github.com/NVlabs/stylegan2/commit/23f8bed55f4b220c69cff98139a000d4c77cd558

**Comment by johndpope** [comment]
this does have an updated dockerfile to suppotr cuda 11 + tensorflow 1
https://github.com/NVlabs/stylegan2-ada

**Comment by johndpope** [comment]
Hi Justin,
Merry xmas - I upgraded tensorflow1 -> tensorflow2 and fixed issues using latest cuda 11.2  for running stylegan2-ada locally.
 https://github.com/johndpope/stylegan2-ada (dockerfile is out of date)

also worth checking out - https://github.com/johndpope/stylegan-web
