### ISSUE TITLE
pretrained model for ukiyoe-1024

### ISSUE THREAD

**Issue by betterze** [justinpinkney/toonify#6]
Dear Justin,

Thank you for sharing this nice work. Would you mind uploading the pretrained model for ukiyoe-1024? 

Thank you for your help.

Best Wishes,

Alex

**Comment by justinpinkney** [comment]
Sure, I'll dig it out and share with you shortly

**Comment by betterze** [comment]
@justinpinkney Thanks a lot, I really appreciate it.

**Comment by justinpinkney** [comment]
Here's a link to download the ukiyo-e faces 1024x1024 model I used for some of the toonify stuff. It's a config-e StyleGAN2 model: https://drive.google.com/file/d/1dn2ugKinoT_h1dzRhZF9bn-6zK_r4U3Z/view?usp=sharing

**Comment by betterze** [comment]
thx a lot.
